runtime: nodejs14
instance_class: F1

handlers:

  - url: /(.*\.(html|css|js|svg|png))$
    static_files: static/\1
    upload: static/.*$
    secure: always

  - url: .*
    script: auto
    secure: always

