runtime: java11

handlers:
  - url: .*
    script: auto
    secure: always

instance_class: F4 # 1024 MB / 2.4 GHz

automatic_scaling:
  max_idle_instances: 1 # prevent conflicts when dumping rdf to storage bucket