runtime: java21

handlers:

  - url: /(.*\.(html|css|js|md|svg|png))$
    static_files: static/\1
    upload: static/.*$
    secure: always

  - url: /.*
    script: auto
    secure: always

instance_class: F1 # https://cloud.google.com/appengine/docs/standard#instance_classes

automatic_scaling:
  max_instances: 1
