/*
 * Copyright © 2020-2025 EC2U Alliance
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eu.ec2u.data._resources;

import com.metreeca.mesh.meta.jsonld.*;
import com.metreeca.mesh.meta.jsonld.Class;
import com.metreeca.mesh.meta.shacl.Required;

import eu.ec2u.data._datasets.Dataset;
import eu.ec2u.data._universities.University;

import java.net.URI;
import java.util.Set;

import static eu.ec2u.data.__._EC2U.BASE;

@Frame
@Class
@Base(BASE)
@Namespace(prefix="[ec2u]", value="/terms/")
public interface Resource extends Reference {

    /**
     * @return {@code true}, if the resource is even partially generated by AI tools; {@code false}, otherwise
     */
    Boolean generated();


    @SuppressWarnings("NonBooleanMethodNameMayNotStartWithQuestion")
    URI isDefinedBy();

    @Property("rdfs:")
    Set<URI> seeAlso();

    @Required
    Dataset dataset();

    University university();

}
