/*
 * Copyright © 2020-2025 EC2U Alliance
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eu.ec2u.data._resources;

import com.metreeca.mesh.mint.jsonld.Base;
import com.metreeca.mesh.mint.jsonld.Frame;
import com.metreeca.mesh.mint.jsonld.Namespace;
import com.metreeca.mesh.mint.jsonld.Property;

import java.net.URI;
import java.util.Set;

@Frame
@Base("https://data.ec2u.eu/")
@Namespace(prefix="ec2u", value="/terms/")
public interface Resource extends Reference {

    @Property("rdfs:")
    URI isDefinedBy();

    @Property("rdfs:")
    Set<URI> seeAlso();


    /**
     * @return {@code true}, if the resource is even partially generated by AI tools; {@code false}, otherwise
     */
    @Property("ec2u:")
    boolean generated();

}
